# -*- coding: utf-8 -*-
"""Data Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h6BDeIUhmWU5H2GdvGZdu2EtNnMpj2TL
"""

import matplotlib.pyplot as plt

x=[1,2,3,4,5]
y=[2,4,6,8,10]

plt.plot(x,y)
plt.show()

plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.title("hello Graph\nFirst Graph")
plt.plot(x,y)
plt.show()

x1=[1,3,5,7,9]
plt.plot(x,y,label="first line")
plt.plot(x1,x,label="second line")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.title("hello Graph\nFirst Graph")
plt.legend()
plt.show()

import numpy as np
import math

x=np.arange(0,math.pi*4,0.01)
y=np.sin(x)
plt.plot(x,y)
plt.xlabel("angle")
plt.ylabel("sin-value")
plt.title("Sin graph")

from pylab import *
x = linspace(-3, 3)
y = x**2
plot(x, y, 'r-.')
show()

"""# **Barchart**

*bar(x,y,width,bottom,align,data,**kwargs)*
"""

x=[1,2,3,4,5]
y=[2,4,11,8,10]

plt.bar(x,y)

x=[1,2,3,4,5]
y=[2,4,11,8,10]

plt.barh(x,y)

s_class=[9,10,11,12]
boys=[60,50,90,85]
girls=[45,45,100,90]

bar1=[i+0.4 for i in s_class]
bar2=[i+0.2 for i in s_class]


plt.bar(s_class,boys,0.4,label="Boys")
plt.bar(bar1,girls,0.4,label="Girls")

plt.xticks(bar2,s_class)

plt.title("Student vs class")
plt.xlabel("Class")
plt.ylabel("No. of Students")
plt.legend()

"""# Histogram"""

from random import randint
x=[randint(15,80) for i in range(100)]
y=[20,30,40,50,60,70,80]

plt.hist(x,bins=y,ec='red')
plt.title('Histogram of Age')
plt.xlabel("Age Group")
plt.ylabel("No. of Students")

"""# Pie Chart

pie(x, explode=None, labels=None, colors=None, autopct=None, pctdistance=0.6, shadow=False, labeldistance=1.1, startangle=None, radius=None, counterclock=True, wedgeprops=None, textprops=None, center=(0, 0), frame=False, rotatelabels=False, *, data=None)
"""

x=[5468,7665,2767,7560]
y=["C","Python","C++","Java"]
explode=[0,0.2,0,0]

plt.pie(x,labels=y,wedgeprops={"edgecolor":"black"},shadow=True,explode=explode,startangle=90);

x=[10,23,44,63,35,81,74,91,55,66]
y=[4,6,2,8,9,10,12,18,1,7]
z=[5,6,7,8,13,16,9,8,10,12]
plt.scatter(x,y,edgecolor='red',c="green",s=100)

"""# 3D GRAPH"""

from mpl_toolkits import mplot3d
import numpy as np

fig=plt.figure()
ax1=fig.add_subplot(111, projection='3d')

x=[1,2,3,4,5,6,7,8,9]
y=[5,6,7,8,13,16,9,8,10]
z=np.zeros(9)

ax1.plot3D(x,y,z,color='brown',label="line")

ax1.set_xlabel("x-axis")
ax1.set_ylabel("y-axis")
ax1.set_zlabel("z-axis")
ax1.legend()

plt.show()

fig=plt.figure()
ax1=fig.add_subplot(111, projection='3d')

x=[1,2,3,4,5,6,7,8,9]
y=[5,6,7,8,13,16,9,8,10]
z=np.zeros(9)

dx=np.ones(9)
dy=np.ones(9)
dz=[1,2,4,6,8,5,8,3,9]

ax1.bar3d(x,y,z,dx,dy,dz,color='red')

ax1.set_xlabel("x-axis")
ax1.set_ylabel("y-axis")
ax1.set_zlabel("z-axis")

fig=plt.figure()
ax1=fig.add_subplot(111, projection='3d')

x=[1,2,3,4,5,6,7,8,9]
y=[5,6,7,8,13,16,9,8,10]
z=[1,2,7,8,5,6,4,9,10]

w=[4,6,3,7,2,9,4,5,0]

ax1.scatter3D(x,y,z,cmap='Greens',c=w,s=100)
ax1.set_xlabel("x-axis")
ax1.set_ylabel("y-axis")
ax1.set_zlabel("z-axis")

plt.show()

!pip install bar_chart_race

!pip install ffmpeg-python

import bar_chart_race  as bcr
import pandas as pd

df=pd.read_csv(r"C:\Users\maverick\Documents\state_wise_daily_covid.csv")

df.tail()

df=df.set_index("Date")
df=df.drop("Status",axis=1)

df.head()

import pandas as pd
data = pd.read_csv("/content/titanic_train.csv")

data.columns

import seaborn as sns

graph = sns.barplot(data["Survived"], data["Sex"]);

data.head(20)

data.count()

description = data.describe()
description

sns.displot( data["Survived"] );

sns.barplot(data["Sex"], data["Age"]);